name: Chrome WebDriver Debug

on:
  workflow_dispatch:

env:
  DISPLAY: ":99.0"

jobs:
  debug-chrome:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
    
    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        
        # Install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Setup virtual display
        Xvfb :99 -screen 0 1280x720x24 > /dev/null 2>&1 &
        sleep 3
        
        # Install ChromeDriver
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3)
        echo "Chrome version: $CHROME_VERSION"
        CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d'.' -f1)
        echo "Chrome major: $CHROME_MAJOR"
        
        # Download matching ChromeDriver
        if [ $CHROME_MAJOR -ge 115 ]; then
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json" | python3 -c "import json,sys; data=json.load(sys.stdin); print(data['channels']['Stable']['version'])" 2>/dev/null || echo "")
          if [ -n "$CHROMEDRIVER_VERSION" ]; then
            CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
            wget -q "$CHROMEDRIVER_URL" -O chromedriver.zip
            unzip -q chromedriver.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
            rm -rf chromedriver.zip chromedriver-linux64/
          fi
        fi
        
        # Verify installations
        google-chrome --version
        /usr/local/bin/chromedriver --version
    
    - name: Debug Step 1 - Minimal Chrome Test
      run: |
        echo "=== 最小構成Chrome起動テスト ==="
        python debug_chrome_minimal.py
    
    - name: Debug Step 2 - Verbose Logging
      run: |
        echo "=== 詳細ログ収集 ==="
        python debug_chrome_verbose.py
    
    - name: System Info
      if: always()
      run: |
        echo "=== システム情報 ==="
        free -h
        ps aux | grep chrome || true
        dmesg | tail -20 || true
        ls -la /usr/local/bin/ | grep driver || true